Revert "vx7r2cert: libgcc routines currently provided by certKernel"
This reverts commit 3185128f999253471ff9f889972d5006fe44b577,
which we believe is causing problems when trying to build programs
using the light and light-tasking runtimes. In particular, we're
getting undefined references to __builtin_clzl. This is visible
for instance when trying to run the ACATS-4 testsuite:

    | in function `system__gcc__ti__udiv_mod_4__udivmod4':
    |  (.text.system__gcc__ti__udiv_mod_4__udivmod4+0xf7):
    |  undefined reference to `__builtin_clzl'

Change-Id: I36d7ab4edc55bc9b52a7b65448ea0423b97504ca
TN: U208-002